name: ezytransit_innerve
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  shared_preferences: ^2.2.2
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.0
  permission_handler: ^11.2.0
  flutter_map: ^6.1.0
  latlong2:
  google_maps_flutter: ^2.5.3
  google_maps_directions: ^0.0.4
  flutter_polyline_points: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/ezytranzit.png
    - assets/images/ezytranzit.svg
    - assets/images/ezytranzit-new.png
    - assets/images/bus.png
    - assets/images/crowd.png
    - assets/images/Routes.png
    - assets/images/Source.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ezytranzit-logo.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/images/ezytranzit-logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
