// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcPcwkEdEubitu1YTRa271vmbjuk4bcEQ',
    appId: '1:470400812857:web:8f85d32a9af677b5108ae8',
    messagingSenderId: '470400812857',
    projectId: 'ezytransit-innerve',
    authDomain: 'ezytransit-innerve.firebaseapp.com',
    storageBucket: 'ezytransit-innerve.appspot.com',
    measurementId: 'G-J8JBX4GM74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Q1mbrLzv1tlYnhzLk2OyNbuz7aFsUPU',
    appId: '1:470400812857:android:5be439b49df1538e108ae8',
    messagingSenderId: '470400812857',
    projectId: 'ezytransit-innerve',
    storageBucket: 'ezytransit-innerve.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ-1EIqTxVDsoQm7jORz-RbFu7B2_2Ro4',
    appId: '1:470400812857:ios:3d228af08903f5d7108ae8',
    messagingSenderId: '470400812857',
    projectId: 'ezytransit-innerve',
    storageBucket: 'ezytransit-innerve.appspot.com',
    iosBundleId: 'com.example.ezytransitInnerve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ-1EIqTxVDsoQm7jORz-RbFu7B2_2Ro4',
    appId: '1:470400812857:ios:eeecbe0f591712a5108ae8',
    messagingSenderId: '470400812857',
    projectId: 'ezytransit-innerve',
    storageBucket: 'ezytransit-innerve.appspot.com',
    iosBundleId: 'com.example.ezytransitInnerve.RunnerTests',
  );
}
